apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-bar
  namespace: http-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-bar
  template:
    metadata:
      labels:
        app: echo-bar
    spec:
      containers:
        - name: echo-bar
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=bar"
            - "-listen=:5678"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: svc-bar
  namespace: http-echo
spec:
  selector:
    app: echo-bar
  ports:
    - port: 5678
      targetPort: 5678
